Amount = "Amount"
ContractingParty = "Contracting Party"
CustomerIdentifier = "Customer Number"
Date = "Date"
Discount = "Discount"
DueDate = "Due date"
Gross = "Gross"
InvoiceNumber = "Invoice no."
Name = "Name"
Net = "Net"
OfferNumber = "Offer no."
PageNumberWithTotalCount = "Page {{.PageNumber}} from {{.PageCount}}"
PaymentReference = "Payment-Reference"
RemittanceInformation = "Transaction-Text"
Tax = "Tax"
