global:
  scrape_interval: 5s
  external_labels:
    monitor: 'golangsvc' 

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: 'golangsvc'
    scrape_interval: 4s
    static_configs:
      - targets: ['service:8080']
